# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - oldrel
  - release
  - devel
warnings_are_errors: true
after_success:
  - Rscript -e 'covr::codecov()'
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip libffi-dev libssl-dev
  - pip3 install pyopenssl ndg-httpsclient pyasn1
  - pip3 install tdda
