library(shinystat)

context('console.R: reading data to global environment')

test_that('all dataframes are created', {
  expect_false( exists('machines_boxes') )
  expect_false( exists('machines_states') )
  expect_false( exists('machines_tubes') )
  expect_false( exists('time_max') )
  expect_false( exists('time_warmup') )
  expect_false( exists('qc_cycles') )
  expect_false( exists('qc_buffer') )
  expect_false( exists('stacker_boxes') )
  expect_false( exists('transferlids') )
  expect_false( exists('warehouse_pallets') )
  expect_false( exists('warehouse_output') )
  expect_false( exists('lifter_states') )
  expect_false( exists('loop_boxes') )

  read_data_frames('data/Exp_14_09_standard_rds/', 'standard')

  expect_true( exists('machines_boxes') )
  expect_true( exists('machines_states') )
  expect_true( exists('machines_tubes') )
  expect_true( exists('time_max') )
  expect_true( exists('time_warmup') )
  expect_true( exists('qc_cycles') )
  expect_true( exists('qc_buffer') )
  expect_true( exists('stacker_boxes') )
  expect_true( exists('transferlids') )
  expect_true( exists('warehouse_pallets') )
  expect_true( exists('warehouse_output') )
  expect_true( exists('lifter_states') )
  expect_true( exists('loop_boxes') )
})
