library(shiny)
library(shinyBS)
library(easyshiny)
library(ggplot2)

es_init()
es_renderText({'This is a simple test if elements are inserted into the app.'}, tab = 'Text')
es_add_input(textInput, inputId = 'title', label = 'Title:', tab = 'Plot')
es_renderPlot({qplot(mtcars$mpg) + ggtitle(label = input$title)}, tab = 'Plot')
es_start(title = 'tabsApp')
